#!/bin/sh

# /etc/profile

# system wide environment and startup programs

appendpath () {
    case ":$PATH:" in
        *:"${1%/}":*) ;;
        *) PATH="${PATH:+$PATH:}${1%/}"
    esac
}

# set our default path (/usr/sbin:/sbin:/bin included for non-void chroots)
appendpath "/usr/local/sbin"
appendpath "/usr/local/bin"
appendpath "/usr/bin"
appendpath "/usr/sbin"
appendpath "/sbin"
appendpath "/bin"

unset appendpath
export PATH

# set default umask
umask 022

# set runtime dir
test -z "$XDG_RUNTIME_DIR" && export XDG_RUNTIME_DIR="/tmp/runtime.${EUID:-${UID:-$(id -u)}}"

# create runtime dir
test ! -d "$XDG_RUNTIME_DIR" && mkdir -pm 0700 "$XDG_RUNTIME_DIR"

# load profiles from /etc/profile.d
if [ -d /etc/profile.d/ ]; then
    for f in /etc/profile.d/*.sh; do
        [ -r "$f" ] && . "$f"
    done
    unset f
fi
